### ISSUE TITLE
MIgrate the wiki pages under Supporting documentation

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/oslc-core#4]
Source: https://wiki.oasis-open.org/oslc-core/FrontPage

**Comment by berezovskyi** [comment]
@jamsden ready for your review. Actually, I dusted off my make skills and came up with this:

```make
INPUT=$(wildcard src-docbook/*)
OUTPUT=$(patsubst src-docbook/%,out-markdown/%.md,$(INPUT))

.PHONY: all
all : $(OUTPUT)

out-markdown/%.md: src-docbook/%
	pandoc -f docbook -t gfm -o $@ $^
```

Turns out Creole implementation in Github is buggy and messes up external links. The conversion with Pandoc messed up multi-level lists. So, I used Docbook export instead and converted everything into Markdown for future editing.

**Comment by berezovskyi** [comment]
See https://github.com/oasis-tcs/oslc-core/wiki for the results. Github does not support multi-level page hierarchies so we will need to get creative with page prefixes and/or organise the homepage better.

**Comment by jamsden** [comment]
Use HTML lists to create a custom sidebar to organize the documents. See 
https://help.github.com/articles/creating-a-sidebar/ 

Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by jamsden** [comment]
Where's https://wiki.oasis-open.org/oslc-core/?

I see there's some quirkiness in how the content gets migrated. But its 
fine. Thanks for doing this.


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by berezovskyi** [comment]
@jamsden yes I saw the extra sidebar but it won't hide the main one, so I don't think it will make the experience better in the end. I think we should make a nice Home page so that people don't use the sidebar at all but the hyperlinks.

@jamsden I did not migrate the home page because: a) the relative links likely won't work and b) we should rearrange the whole homepage to reflect the current direction of the TC.

**Comment by berezovskyi** [comment]
I would also approach the wiki homepage design from the point of view of the first entry. In other words, we should expect someone who has never heard about OSLC, landed on this git repo, read the README full of OASIS legalibberish and clicked "wiki".

**Comment by berezovskyi** [comment]
@jamsden just added a "TC work" wiki page under https://github.com/oasis-tcs/oslc-core/wiki. The idea I have right now is to keep the wiki home page for "what is OSLC" kind of page with pointers to open-services.net. The second page in the sidebar is "our" wiki page containing all the necessary information about the TC work. The middle section should have a current status table for the specs and (maybe) the links to the rest of the wiki pages.

**Comment by berezovskyi** [comment]
Done
