### ISSUE TITLE
Check how rdfs:seeAlso renders in Protege

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/oslc-core#8]
The idea is to remove the rdfs:seeAlso properties from our RDF documents (vocabs and shapes). We need to check how would they show up in a tool like Protege.

**Comment by berezovskyi** [comment]
blocked by https://github.com/protegeproject/protege-distribution/issues/19

**Comment by berezovskyi** [comment]
Manual import of the Turle file showed no rdfs:seeAlso properties:

![image](https://user-images.githubusercontent.com/64734/51330757-6c7c6480-1a78-11e9-8b69-280dfbf41efe.png)

![image](https://user-images.githubusercontent.com/64734/51330766-700feb80-1a78-11e9-88b4-3e3b359e6dbd.png)

**Comment by berezovskyi** [comment]
@jamsden could you please tell me if I am checking the wrong file?

**Comment by jamsden** [comment]
Core doesn't have any rdfs:seeAlso properties, we removed they quite a while ago.

Try the QM vocabulary or shapes https://github.com/oasis-tcs/oslc-domains/tree/master/qm

**Comment by berezovskyi** [comment]
Thanks Jim, will check QM instead.

--
/Andrew

17 jan. 2019 kl. 18:54 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


Core doesn't have any rdfs:seeAlso properties, we removed they quite a while ago.

Try the QM vocabulary or shapes https://github.com/oasis-tcs/oslc-domains/tree/master/qm

**Comment by berezovskyi** [comment]
I can confirm that the links are displayed prominently on the ontology level and we can safely remove the triples in question from individual properties:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/64734/51387329-f33b4b00-1b25-11e9-9e9f-c8bde1438eeb.png">

I will unassign myself, @jamsden, will you do the fix on the vocabulary iself?
